version: '3.8'

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=S3nh@Fatur@2024  
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"  
    volumes:
      - sqlserver-data:/var/opt/mssql  
      - ./sqlserver-entrypoint.sh:/usr/src/app/sqlserver-entrypoint.sh  
      - ./sqlserver.sql:/usr/src/app/sqlserver.sql 
    entrypoint: /bin/bash /usr/src/app/sqlserver-entrypoint.sh  

volumes:
  sqlserver-data:
    driver: local 
